name: Main

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-vala:
    name: Lint vala files
    runs-on: alt-sisyphus
    container:
      image: altlinux.space/alt-gnome/vala-linter-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint files
        uses: alt-gnome/linters-actions/vala@main

  lint-blp:
    name: Lint blueprint UI files
    runs-on: alt-sisyphus
    container:
      image: altlinux.space/alt-gnome/gtk-blueprint-compiler-image:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint files
        uses: alt-gnome/linters-actions/blueprint@main

  checkers:
    name: Run checkers
    runs-on: alt-sisyphus

    steps:
      - name: Update apt cache
        run: apt-get -y update

      - name: Install git and python
        run: apt-get install -y git python3

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run indentation checker
        run: python3 vala-checkers/indentation_checker.py .

      - name: Run empty lines checker
        run: python3 vala-checkers/empty_lines_checker.py .

  build-altlinux:
    name: Build RPM for altlinux

    runs-on: alt-sisyphus
    container:
      image: altlinux.space/rirusha/riru-build-image:latest
    needs:
      - lint-vala
      - lint-blp
      - checkers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gear repo
        run: rbu install-deps

      - name: Build RPM
        run: rbu test

      - name: Upload RPM
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: rbu-altlinux-rpms.zip
          path: |
            ~/.cache/hasherc/riru-build-utils/out/RPMS/*/*.rpm
