name: CI Pull Request

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-vala:
    name: Lint vala files
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Vala
        run: io.elementary.vala-lint -d . -c vala-lint.conf

  lint-blp:
    name: Lint blueprint ui files
    runs-on: ubuntu-latest
    needs: lint-vala

    container:
      image: ubuntu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update apt cache
        run: apt-get update

      - name: Install blueprint-compiler Blueptint
        run: apt-get install -y blueprint-compiler
        
      - name: Lint Blueprint
        run: blueprint-compiler format -s 2 app/data/ui/*.blp

  checkers:
    name: Run checkers
    runs-on: ubuntu-latest
    needs: lint-blp

    container:
      image: ubuntu:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update apt cache
        run: apt-get update

      - name: Install python
        run: apt-get install -y python3.12

      - name: Run indentation checker
        run: python3.12 ./vala-checkers/indentation_checker.py .

      - name: Run empty lines checker
        run: python3.12 ./vala-checkers/empty_lines_checker.py .

  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    needs: checkers

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests and lint
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: foldy.flatpak
        manifest-path: build-aux/flatpak/org.altlinux.Foldy.yml
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }} 
